# Makefile

CXX = gcc
CXXFLAGS = -Wall -O2

all: p1a p1b p2

p1a: p1a.cpp
	$(CXX) $(CXXFLAGS) -o p1a p1a.cpp

p1b: p1b.cpp
	$(CXX) $(CXXFLAGS) -o p1b p1b.cpp

p2: p2.cpp
	$(CXX) $(CXXFLAGS) -o p2 p2.cpp

clean:
	rm -f p1a p1b p2
